format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

command_timeout = 3000

# [username]
# show_always = true

[hostname]
ssh_only = true
ssh_symbol = ""

[git_branch]
symbol = ""
