format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$aws\
$line_break\
$character
"""

command_timeout = 3000

[username]
show_always = false

[hostname]
ssh_only = false
trim_at = ""
ssh_symbol = ""
detect_env_vars = ['!KITTY_WINDOW_ID']

[git_branch]
symbol = ""

[os]
disabled = true
style = "white bold"

[os.symbols]
Macos = ""
Debian = "D | "
