format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$aws\
$line_break\
$character
"""

command_timeout = 3000

# [username]
# show_always = true

[hostname]
ssh_symbol = ""

[git_branch]
symbol = ""

[os]
disabled = false
style = "blue bold"

[os.symbols]
Macos = ""
Debian = "Debian "
