format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$line_break\
$character
"""

command_timeout = 1000
add_newline = true

[hostname]
ssh_only = true
ssh_symbol = ""

[git_branch]
symbol = ""
