theme = "varua"
# varua
# boo_berry
# autumn
# github_dark_tritanopia

[editor]
true-color = true
bufferline = "always"
auto-save = true

[keys.normal]
"C-p" = "file_picker"
"C-o" = "command_palette"
# "C-/" = "toggle_comments"
"C-s" = ":w!"
"C-w" = ":buffer-close"

# EXPERIMENTAL
# "q"   = "no_op"
"q" = "move_prev_word_start"
"Q" = "move_prev_long_word_start"
"esc" = "keep_primary_selection"
"G" = "goto_last_line"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
right = ["diagnostics", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

# TODO
# refresh file if there are changes
# autosave
# trim spaces
# copy paste
# undo redo
