function mashina_debug {
  # echo "MASHINA_IS_LOADED: $MASHINA_IS_LOADED"
  # echo "MASHINA_IS_FRESH: $MASHINA_IS_FRESH"
  echo "MASHINA_IS_DEBIAN: $MASHINA_IS_DEBIAN"
  echo "MASHINA_IS_MACOS: $MASHINA_IS_MACOS"
  echo "MASHINA_IS_BASH: $MASHINA_IS_BASH"
  echo "MASHINA_IS_ZSH: $MASHINA_IS_ZSH"
  echo "PATH: $PATH"
}
