AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99

Naming/VariableNumber:
  EnforcedStyle: snakecase

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
