source "$MASHINA_SOURCE/lib/is_variable_defined.sh"
source "$MASHINA_SOURCE/lib/default_editor.sh"
source "$MASHINA_SOURCE/lib/is_zsh.sh"
source "$MASHINA_SOURCE/lib/is_bash.sh"
source "$MASHINA_SOURCE/lib/is_macos.sh"
source "$MASHINA_SOURCE/lib/is_debian.sh"
source "$MASHINA_SOURCE/lib/version.sh"
